### ISSUE TITLE
getting started example not working

### ISSUE THREAD

**Issue by segator** [fluidattacks/makes-example#36]
the example in makes page fails :(
` m github:fluidattacks/makes-example@main`

```
this derivation will be built:
  /nix/store/118d5m6azm08j65f4152krvc04lssv8i-config.json.drv
building '/nix/store/118d5m6azm08j65f4152krvc04lssv8i-config.json.drv'...
/nix/store/r23xy6nkc86zlaq1y0p1s9wk731rx522-config.json
Traceback (most recent call last):
  File "/nix/store/jaxaqynsvz0jlcv0wjsc0fmz6awi9dqv-src/src/cli/main/__main__.py", line 7, in <module>
    main(sys.argv)
  File "/nix/store/jaxaqynsvz0jlcv0wjsc0fmz6awi9dqv-src/src/cli/main/cli.py", line 786, in main
    cli(args)
  File "/nix/store/jaxaqynsvz0jlcv0wjsc0fmz6awi9dqv-src/src/cli/main/cli.py", line 576, in cli
    args, attr = _cli_get_args_and_attr(args, config.attrs, src)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jaxaqynsvz0jlcv0wjsc0fmz6awi9dqv-src/src/cli/main/cli.py", line 601, in _cli_get_args_and_attr
    args = [*args[0:2], *_help_picking_attr(src, attrs)]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jaxaqynsvz0jlcv0wjsc0fmz6awi9dqv-src/src/cli/main/cli.py", line 546, in _help_picking_attr
    TextUserInterface.run(
TypeError: App.run() got an unexpected keyword argument 'attrs'
```

**Comment by dsalaza4** [comment]
Hi @segator,

We will be updating the entire repo soon and let you know. 

This is most likely caused by a breaking change introduced in one of the latest releases of Makes.
